<?php

/**
 * @file
 * Webform Analysis - Module.
 */

/**
 * Implements hook_theme().
 */
function webform_analysis_theme() {
  return [
    'webform_analysis_component' => [
      'variables' => [
        'name'  => '',
        'title' => '',
        'data'  => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_entity_type_build().
 */
function webform_analysis_entity_type_build(array &$entity_types) {
  $entity_types['webform']->setFormClass('analysis', 'Drupal\webform_analysis\Form\WebformAnalysisForm');
}